repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        additional_dependencies:
          - pydantic
          - rich 
          - typer 
          - alembic 
          - duckdb
          - pytest


  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run --locked pytest
        language: system
        pass_filenames: false
        args: [-ra, --cov=src]
