repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
    -   id: ruff
        args: [--fix]
        exclude: ^tests/
    -   id: ruff-format
        exclude: ^tests/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
    -   id: mypy
        exclude: ^tests/
        additional_dependencies:
            - pydantic
