"""Initial schema setup

Revision ID: 53dc9abc36a8
Revises: 
Create Date: 2025-03-29 13:34:36.043682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53dc9abc36a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storms',
    sa.Column('storm_id', sa.String(), nullable=False, doc="Unique storm identifier (e.g., 'AL012023')"),
    sa.Column('basin', sa.String(), nullable=False, doc="Basin code (e.g., 'AL' for Atlantic)"),
    sa.Column('cyclone_number', sa.Integer(), nullable=False, doc="ATCF cyclone number"),
    sa.Column('year', sa.Integer(), nullable=False, doc="Year of the storm"),
    sa.Column('name', sa.String(), nullable=False, doc="Storm name or 'UNNAMED'"),
    sa.CheckConstraint("basin IN ('AL', 'EP', 'CP')", name=op.f('check_basin')),
    sa.CheckConstraint('cyclone_number > 0', name=op.f('check_cyclone_number')),
    sa.CheckConstraint('year >= 1851', name=op.f('check_year')),
    sa.PrimaryKeyConstraint('storm_id', name=op.f('pk_storms')),
    sa.UniqueConstraint('basin', 'cyclone_number', 'year', name=op.f('uix_storm'))
    )
    op.create_table('observations',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, doc="Unique observation ID"), # Explicitly set autoincrement=False
    sa.Column('storm_id', sa.String(), nullable=False, doc="Foreign key to storms table"),
    sa.Column('date', sa.DateTime(), nullable=False, doc="Observation timestamp"),
    sa.Column('record_identifier', sa.String(), nullable=True, doc="Optional record identifier (e.g., 'L' for landfall)"),
    sa.Column('status', sa.String(), nullable=False, doc="Storm status (e.g., 'HU' for hurricane)"),
    sa.Column('location_wkt', sa.String(), nullable=False, doc="Location in WKT format (e.g., 'POINT(-80.0 25.0)')"),
    sa.Column('max_wind', sa.Integer(), nullable=True, doc="Maximum sustained wind speed in knots"),
    sa.Column('max_wind_mph', sa.Float(), nullable=True, doc="Maximum sustained wind speed in mph"),
    sa.Column('min_pressure', sa.Integer(), nullable=True, doc="Minimum pressure in millibars"),
    sa.Column('ne34', sa.Integer(), nullable=True, doc="Northeast 34-knot wind radius in nautical miles"),
    sa.Column('se34', sa.Integer(), nullable=True, doc="Southeast 34-knot wind radius in nautical miles"),
    sa.Column('sw34', sa.Integer(), nullable=True, doc="Southwest 34-knot wind radius in nautical miles"),
    sa.Column('nw34', sa.Integer(), nullable=True, doc="Northwest 34-knot wind radius in nautical miles"),
    sa.Column('ne50', sa.Integer(), nullable=True, doc="Northeast 50-knot wind radius in nautical miles"),
    sa.Column('se50', sa.Integer(), nullable=True, doc="Southeast 50-knot wind radius in nautical miles"),
    sa.Column('sw50', sa.Integer(), nullable=True, doc="Southwest 50-knot wind radius in nautical miles"),
    sa.Column('nw50', sa.Integer(), nullable=True, doc="Northwest 50-knot wind radius in nautical miles"),
    sa.Column('ne64', sa.Integer(), nullable=True, doc="Northeast 64-knot wind radius in nautical miles"),
    sa.Column('se64', sa.Integer(), nullable=True, doc="Southeast 64-knot wind radius in nautical miles"),
    sa.Column('sw64', sa.Integer(), nullable=True, doc="Southwest 64-knot wind radius in nautical miles"),
    sa.Column('nw64', sa.Integer(), nullable=True, doc="Northwest 64-knot wind radius in nautical miles"),
    sa.Column('max_wind_radius', sa.Integer(), nullable=True, doc="Radius of maximum wind in nautical miles"),
    sa.CheckConstraint("status IN ('TD', 'TS', 'HU', 'EX', 'SD', 'SS', 'LO', 'WV', 'DB')", name=op.f('check_status')),
    sa.CheckConstraint('max_wind IS NULL OR max_wind >= 0 OR max_wind IN (-999, -99)', name=op.f('check_max_wind')),
    sa.CheckConstraint('min_pressure IS NULL OR min_pressure >= 0 OR min_pressure IN (-999, -99)', name=op.f('check_min_pressure')),
    sa.ForeignKeyConstraint(['storm_id'], ['storms.storm_id'], name=op.f('fk_observations_storm_id_storms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observations')
    op.drop_table('storms')
    # ### end Alembic commands ###
